### ISSUE TITLE
[Issue] dotLX8 application fails to launch

### ISSUE THREAD

**Issue by Shadpw2** [RyanWalpoleEnterprises/Moxo-QuickWeb#9]
### The Issue or Bug

upon build & launch, applications states "Argument 'picture' must be a picture that can be used as a icon." Despite having an icon file present.
![image](https://user-images.githubusercontent.com/30399377/226756104-8a0592fd-84f1-4f88-8a09-4577478c9d39.png)

### Version

230302(01502103P)

### Operating System

Windows 10

### Steps to reproduce the behavior

1. Open Dashboarc
2. select "get started" for the DotLX8 type.
3. enter relevant fields
4. select build and close Moxo
5. extract .zip
6. Run Application.

### Additional Context

[ChatGPT.zip](https://github.com/RyanWalpoleEnterprises/Moxo-QuickWeb/files/11034387/ChatGPT.zip)

### Suggested Resolution

I'm thinking the .ico isn't a valid .ico but windows 10 seems to think it is. 
probably my fault.

**Comment by RyanWalpole** [comment]
**Triage**
Can not replicate this issue with self made projects, seems to be isolated to this project.
User notes possibility that the ICO file is not valid.  Will attempt to investigate project type with this in mind.

**Comment by RyanWalpole** [comment]
How did you go about obtaining your ICO file? Did you use an online convert tool to convert PNG to ICO and if so, which tool?  @Shadpw2 

Seems that the ICO is actually a PNG, mime type reporting ``image/png`` via Exif Metadata.
![image](https://user-images.githubusercontent.com/69621127/226765093-cc160906-c766-4f7e-8e32-a820b099264e.png)

- [ ] Add failsafe for incorrectly formatted ``image/png``
- [ ] Add proper error code for error ``Argument 'picture' must be a picture that can be used as an icon``
- [ ] Include notes in documentation and reference material.

**Comment by RyanWalpole** [comment]
## Solution
**Implement error code as seen below:**
| Error Code     	| Error                                                                                                                       	| Details                                                                                                  	| dotLX 	| .NET 	|
|----------------	|-----------------------------------------------------------------------------------------------------------------------------	|----------------------------------------------------------------------------------------------------------	|-------	|------	|
MOXDLX035A-01H 	| The icon supplied is not a valid icon file.                                                                                 	| - The icon file supplied does not have a supported MIME type. Could this be a renamed PNG?               	| ✅     	|      	|

**Implement code to detect the MIME type when a file is selected**
```
                byte[] buffer = new byte[256];
                using (FileStream fs = new FileStream(filePath, FileMode.Open, FileAccess.Read))
                {
                    fs.Read(buffer, 0, 256);
                }

                // Determine the mime type using the FindMimeFromData function
                uint mimeType;
                FindMimeFromData(0, null, buffer, 256, null, 0, out mimeType, 0);

                // Convert the mime type from a uint to a string
                string mimeTypeString = Marshal.PtrToStringUni((IntPtr)mimeType);

                // Parse the mime type
                //MessageBox.Show(mimeTypeString);
                if (String.IsNullOrWhiteSpace(mimeTypeString))
                {
                    //Cannot determine, assume safe.
                }
                else if (mimeTypeString.Contains("icon"))
                {
                    //Valid icon file
                }
                else if(!mimeTypeString.Contains("icon"))
                {
                    //Does not contain the correct mime type
                    MessageBox.Show("The ico file you selected reported a MIME file type of " + mimeTypeString + "." + Environment.NewLine + Environment.NewLine + "This may not be a valid icon file and may cause issues in your application.", "Warning | Moxo QuickWeb Studio [dotLX]", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
```
**Offer conversion route**
Offer a route for the user to convert an existing PNG to ICO file.
